FROM node:18-alpine

WORKDIR /app

COPY package.json nest-cli.json tsconfig.build.json tsconfig.json ./

RUN npm install

COPY /apps/distribution ./apps/distribution

ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379

EXPOSE 3001

CMD [ "npm", "run", "start:distribution" ]