FROM node:18-alpine

WORKDIR /app

COPY package.json nest-cli.json tsconfig.build.json tsconfig.json ./

RUN npm install

COPY /apps/distribution ./apps/distribution
COPY /libs ./libs

ENV PORT=3001
ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV RETRY_ATTEMPTS=5
ENV RETRY_DELAY=5000

EXPOSE 3001

CMD [ "npm", "run", "start:distribution" ]