version: '3.8'
services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5762:5762'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq
  notification:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.notification
    ports:
      - '3000:3000'
      - '8000:8000'
    volumes:
      - ./apps/notification:/app/apps/notification
      - ./libs:/app/libs
      - /app/node_modules
    env_file:
      - ./env/notification.env
    tty: true
    stdin_open: true
    depends_on:
      - database
      - redis
  distribution:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.distribution
    ports:
      - '3001:3001'
      - '8001:8001'
    volumes:
      - ./apps/distribution:/app/apps/distribution
      - ./libs:/app/libs
      - /app/node_modules
    env_file:
      - ./env/distribution.env
    tty: true
    stdin_open: true
    depends_on:
      - database
      - rabbitmq
      - redis
  iam:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.iam
    ports:
      - '3002:3002'
      - '8002:8002'
    volumes:
      - ./apps/iam:/app/apps/iam
      - ./libs:/app/libs
      - /app/node_modules
    env_file:
      - ./env/iam.env
    tty: true
    stdin_open: true
volumes:
  pgadmin:
  redis:
  rabbitmq: