version: '3.8'
services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  notification:
    build:
      context: ./
      dockerfile: Dockerfile.notification
    ports:
      - '3000:3000'
    volumes:
      - ./apps/notification:/app/apps/notification
      - ./libs:/app/libs
      - /app/node_modules
    env_file:
      - ./env/notification.env
    tty: true
    stdin_open: true
    depends_on:
      - database
      - redis
  distribution:
    build:
      context: ./
      dockerfile: Dockerfile.distribution
    ports:
      - '3001:3001'
    volumes:
      - ./apps/distribution:/app/apps/distribution
      - ./libs:/app/libs
      - /app/node_modules
    env_file:
      - ./env/distribution.env
    tty: true
    stdin_open: true
    depends_on:
      - database
      - redis
volumes:
  pgadmin:
  redis: