apiVersion: v1
kind: ConfigMap
metadata:
  # Fixme: Decide how the name should be handled. (Release name vs. Chart Name)
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes