apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: {{ toYaml .Values.selectorLabels | nindent 4 }}
  # Todo: Update values.yaml to support defining the service type.
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.ports.client }}
      targetPort: {{ .Values.targetPorts.client }}
      name: client
    - protocol: TCP
      port: {{ .Values.ports.gossip }}
      targetPort: {{ .Values.targetPorts.gossip }}
      name: gossip