apiVersion: v1
kind: Service
metadata:
  # Fixme: Decide how the name should be handled. (Release name vs. Chart Name)
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector: {{ toYaml .Values.selectorLabels | nindent 4 }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.ports.client }}
      targetPort: {{ .Values.targetPorts.client }}
      name: client
    - protocol: TCP
      port: {{ .Values.ports.gossip }}
      targetPort: {{ .Values.targetPorts.gossip }}
      name: gossip