FROM node:18-alpine

WORKDIR /app

COPY *.json .

RUN npm install

COPY /apps/notification ./apps/notification
COPY /libs ./libs

ENV API_KEY_HEADER='Notification-Api-Key'
ENV PORT=3000
ENV RETRY_ATTEMPTS=5
ENV RETRY_DELAY=5000

EXPOSE 3000

CMD [ "npm", "run", "start:notification" ]