FROM node:18-alpine

WORKDIR /app

COPY *.json .

RUN npm install

COPY /apps/distribution ./apps/distribution
COPY /libs ./libs

ENV PORT=3001
ENV RETRY_ATTEMPTS=5
ENV RETRY_DELAY=5000

EXPOSE 3001

CMD [ "npm", "run", "start:distribution" ]