FROM node:18-alpine

WORKDIR /app

COPY package.json nest-cli.json tsconfig.build.json tsconfig.json ./

RUN npm install

COPY /apps/notification ./apps/notification
COPY /libs ./libs

ENV API_KEY=notification123
ENV PORT=3000
ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV RETRY_ATTEMPTS=5
ENV RETRY_DELAY=5000

EXPOSE 3000

CMD [ "npm", "run", "start:notification" ]