FROM node:18-alpine

WORKDIR /app

COPY *.json .

RUN npm install

COPY /apps/analytics ./apps/analytics
COPY /libs ./libs

ENV NODE_ENV='production'
ENV PORT=3002
ENV RETRY_ATTEMPTS=5
ENV RETRY_DELAY=5000

EXPOSE 3001

CMD [ "npm", "run", "start:analytics" ]