FROM node:18-alpine

WORKDIR /app

COPY *.json .

RUN npm install

COPY /apps/iam ./apps/iam
COPY /libs ./libs

ENV PORT=3002
ENV ENABLE_DEVTOOLS=true
ENV DEVTOOLS_PORT=8002

EXPOSE ${PORT}
EXPOSE ${DEVTOOLS_PORT}

CMD [ "npm", "run", "start:iam" ]
