selectorLabels:
  app: distribution

service:
  type: LoadBalancer
  port: 3001
  targetPort: 3001

deployment:
  replicaCount: 1
  annotations: null

distribution:
  tag: null
  environment: null
  readinessProbe:
    httpGet:
      path: /health
      port: 3001
      httpHeaders:
        - name: Accept
          value: application/json
    initialDelaySeconds: 10
    periodSeconds: 10
  livenessProbe: {}
  resources: {}

openTelemetry:
  enable: false
  tag: null
  resources: {}
  config: null