# Note: Nginx as an api gateway is used to forward traffic to the appropriate service
#       due to limited IP Address assignment for load balanced services. May eventually
#       be replaced with UI's Nginx Server.
# Note: See https://learn.microsoft.com/en-us/azure/aks/static-ip for configuring a DNS
#       label with AKS load balancer.
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: hermes
  annotations:
data:
  default.conf.template: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      #access_log  /var/log/nginx/host.access.log  main;

      location /notification-api/ {
          proxy_pass http://notification.hermes:3000/;
      }

      location /distribution-api/ {
          proxy_pass http://distribution.hermes:3001/;
      }

      location /iam-api/ {
          proxy_pass http://iam.hermes:3002/;
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: hermes
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: ${aksResourceGroup}
    service.beta.kubernetes.io/azure-pip-name: ${publicIPName}
    service.beta.kubernetes.io/azure-dns-label-name: ${uniqueServiceLabel}
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: hermes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nginx:1.24-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: api-gateway-config
              mountPath: /etc/nginx/templates
      volumes:
        - name: api-gateway-config
          configMap:
            name: api-gateway-config
