apiVersion: v1
kind: Service
metadata:
  name: distribution-service
  namespace: hermes
spec:
  selector:
    app: distribution
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distribution-deployment
  namespace: hermes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: distribution
  template:
    metadata:
      labels:
        app: distribution
    spec:
      containers:
        - name: distribution
          image: cmclaughlin24/distribution:latest
          ports:
            - containerPort: 3001
          env:
            - name: API_KEY
              value: 'distribution123'
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbPort
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbName
            - name: RABBITMQ_URI
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: rabbitmqUri
            - name: RABBITMQ_DISTRIBUTION_EXCHANGE
              value: 'distribution'
            - name: RABBITMQ_DISTRIBUTION_DL_ROUTING_KEY
              value: 'dead.letter.distribution'
            - name: RABBITMQ_DL_EXCHANGE
              value: 'dead-letter-exchange'
            - name: RABBITMQ_DISTRIBUTION_QUEUE
              value: 'distribution'
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: redisPort
            - name: ENABLE_REDIS_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: enableRedisCluster
            - name: BULLMQ_NOTIFICATION_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: notificationQueue
            - name: BULLMQ_NOTIFICATION_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: notificationPrefix
            - name: SUBSCRIBERS_REQUEST_URL
              value: SUBSCRIBERS_REQUEST_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 5
            periodSeconds: 5