apiVersion: v1
kind: ConfigMap
metadata:
  name: env-store
data:
  dbHost: ${DB_HOST}
  dbPort: ${DB_PORT}
  dbUsername: ${DB_USERNAME}
  dbPassword: ${DB_PASSWORD}
  dbName: ${DB_NAME}
  redisHost: 'redis-service.default'
  redisPort: '6379'
  notificationQueue: 'notification'