apiVersion: v1
kind: ConfigMap
metadata:
  name: env-store
  namespace: hermes
data:
  dbHost: ${DB_HOST}
  dbPort: ${DB_PORT}
  dbName: ${DB_NAME}
  rabbitmqUri: 'amqp://guest:guest@rabbitmq-service.hermes'
  redisHost: 'redis-cluster-service.hermes'
  redisPort: '6379'
  enableRedisCluster: 'true'
  notificationQueue: 'notification'
  notificationPrefix: '{notification}'
  enableOpenTelemetry: 'true'
  otelExporterOtlpEndpoint: "https://api.honeycomb.io"
  otelExporterOtlpHeaders: "x-honeycomb-team=your-api-key"