apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: cmclaughlin24/notification:latest
          env:
            - name: API_KEY
              value: ''
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbPort
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbName
            - name: MAILER_HOST
              value: ''
            - name: MAILER_PORT
              value: ''
            - name: MAILER_USER
              value: ''
            - name: MAILER_PASSWORD
              value: ''
            - name: MAILER_SENDER
              value: ''
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: redisPort
            - name: BULLMQ_NOTIFICATION_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: notificationQueue
            - name: TWILIO_SID
              value: ''
            - name: TWILIO_AUTH_TOKEN
              value: ''
            - name: TWILIO_PHONE_NUMBER
              value: ''