apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: hermes
spec:
  selector:
    app: notification
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: cmclaughlin24/notification:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              value: ${API_KEY}
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbPort
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: dbName
            - name: MAILER_HOST
              value: ${MAILER_HOST}
            - name: MAILER_PORT
              value: ${MAILER_PORT}
            - name: MAILER_USER
              value: ${MAILER_USER}
            - name: MAILER_PASSWORD
              value: ${MAILER_PASSWORD}
            - name: MAILER_SENDER
              value: ${MAILER_SENDER}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: redisPort
            - name: ENABLE_REDIS_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: enableRedisCluster
            - name: BULLMQ_NOTIFICATION_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: notificationQueue
            - name: BULLMQ_NOTIFICATION_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: env-store
                  key: notificationPrefix
            - name: BULLMQ_NOTIFICATION_JOB_AGE
              value: '86400'
            - name: REMOVE_SUBSCRIBER_URL
              value: distribution-service.hermes:3001/subscription
            - name: SUBSCRIBER_API_KEY_HEADER
              value: Api-Key
            - name: SUBSCRIBER_API_KEY
              value: notification123
            - name: TWILIO_SID
              value: ${TWILIO_SID}
            - name: TWILIO_AUTH_TOKEN
              value: ${TWILIO_AUTH_TOKEN}
            - name: TWILIO_PHONE_NUMBER
              value: ${TWILIO_PHONE_NUMBER}
            - name: VAPID_SUBJECT
              value: ${VAPID_SUBJECT}
            - name: VAPID_PUBLIC_KEY
              value: ${VAPID_PUBLIC_KEY}
            - name: VAPID_PRIVATE_KEY
              value: ${VAPID_PRIVATE_KEY}
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 5
            periodSeconds: 5