# 1) Add Redis Resources to Kubernetes Cluster: kubectl apply -f redis-cluster.yaml
# 2) Get Pod IP Address: kubectl get pods -o wide
# 3) Initialize Cluster: kubectl exec -it redis-cluster-0 -n [CLUSTER NAMESPACE] -- redis-cli --cluster create --cluster-replicas 1 [POD IP_ADDRESS:PORT]
# 4) View Cluster Nodes: for x in $(seq 0 5); do echo "redis-cluster-$x"; kubectl exec redis-cluster-$x -n [CLUSTER NAMESPACE] -- redis-cli role; echo; done 
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
  namespace: hermes
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: client
    - protocol: TCP
      port: 16379
      targetPort: 16379
      name: gossip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: hermes
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: hermes
spec:
  replicas: 6
  serviceName: redis-cluster-service
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          volumeMounts:
            - name: redis-config
              mountPath: /config
            - name: redis-data
              mountPath: /data
          command: ['redis-server', '/config/redis.conf']
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 500M