apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: hermes
data:
  host: ${DB_HOST}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-credentials
  namespace: hermes
data:
  username: ${SENDGRID_USERNAME}
  password: ${SENDGRID_PASSWORD}
  sender: ${SENDGRID_SENDER}
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-credentials
  namespace: hermes
data:
  sid: ${TWILIO_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: vapid-keys
  namespace: hermes
data:
  publicKey: ${VAPID_PUBLIC_KEY}
  privateKey: ${VAPID_PRIVATE_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-credentials
  namespace: hermes
data:
  jwtSecret: ${JWT_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: hermes
data:
  uri: ${RABBITMQ_URI}
