apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cluster-init
  namespace: hermes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-cluster-initializer
  namespace: hermes
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["wait", "get", "exec", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-cluster-initializer-role-bind
  namespace: hermes
subjects:
  - kind: ServiceAccount
    name: redis-cluster-init
roleRef:
  kind: Role
  name: redis-cluster-initializer