selectorLabels:
  app: iam

service:
  type: LoadBalancer
  port: 3002
  targetPort: 3002

deployment:
  replicaCount: 1
  annotations: null

iam:
  tag: null
  environment: null
  readinessProbe: {}
  livenessProbe: {}
  resources: {}

openTelemetry:
  enable: false
  tag: null
  resources: {}
  config: null