name: Build Notfication Service

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'apps/distribution/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/arm64, linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set-up Docker Buildx 
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.prod
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notification:latest
          build-args: |
            APPLICATION=notification
            DEFAULT_PORT=3000